name: Send commits to Discord

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "content": "**New Commit on `'"${GITHUB_REPOSITORY}"'`**\nBranch: `'"${GITHUB_REF#refs/heads/}"'`\nCommit: `'"${GITHUB_SHA}"'`\nAuthor: `'"${GITHUB_ACTOR}"'`\nMessage: `'"${{ github.event.head_commit.message }}"'`"
          }' "$DISCORD_WEBHOOK"
